# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loteriasV1.0.1.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 507)
        MainWindow.setMinimumSize(QtCore.QSize(650, 507))
        MainWindow.setMaximumSize(QtCore.QSize(650, 507))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelDate = QtWidgets.QLabel(self.centralwidget)
        self.labelDate.setGeometry(QtCore.QRect(3, 0, 171, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDate.sizePolicy().hasHeightForWidth())
        self.labelDate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelDate.setFont(font)
        self.labelDate.setText("")
        self.labelDate.setObjectName("labelDate")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 30, 211, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(520, 0, 121, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(8)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumber.setObjectName("lcdNumber")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(9, 90, 631, 361))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.mdiArea.setFont(font)
        self.mdiArea.setViewMode(QtWidgets.QMdiArea.TabbedView)
        self.mdiArea.setDocumentMode(False)
        self.mdiArea.setTabsMovable(True)
        self.mdiArea.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.mdiArea.setTabPosition(QtWidgets.QTabWidget.North)
        self.mdiArea.setObjectName("mdiArea")
        self.Mega = QtWidgets.QWidget()
        self.Mega.setObjectName("Mega")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.Mega)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 461, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalLayoutWidget_2.sizePolicy().hasHeightForWidth())
        self.horizontalLayoutWidget_2.setSizePolicy(sizePolicy)
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.spinBoxDezenasMega_3 = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxDezenasMega_3.sizePolicy().hasHeightForWidth())
        self.spinBoxDezenasMega_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxDezenasMega_3.setFont(font)
        self.spinBoxDezenasMega_3.setMinimum(6)
        self.spinBoxDezenasMega_3.setMaximum(15)
        self.spinBoxDezenasMega_3.setObjectName("spinBoxDezenasMega_3")
        self.horizontalLayout_7.addWidget(self.spinBoxDezenasMega_3)
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.spinBoxJogosMega_3 = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxJogosMega_3.sizePolicy().hasHeightForWidth())
        self.spinBoxJogosMega_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxJogosMega_3.setFont(font)
        self.spinBoxJogosMega_3.setMinimum(1)
        self.spinBoxJogosMega_3.setMaximum(100)
        self.spinBoxJogosMega_3.setObjectName("spinBoxJogosMega_3")
        self.horizontalLayout_7.addWidget(self.spinBoxJogosMega_3)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.Mega)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 100, 461, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalLayoutWidget_5.sizePolicy().hasHeightForWidth())
        self.horizontalLayoutWidget_5.setSizePolicy(sizePolicy)
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ButtonJogarMega_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonJogarMega_3.sizePolicy().hasHeightForWidth())
        self.ButtonJogarMega_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.ButtonJogarMega_3.setFont(font)
        self.ButtonJogarMega_3.setObjectName("ButtonJogarMega_3")
        self.horizontalLayout_8.addWidget(self.ButtonJogarMega_3)
        self.ButtonApagarMega_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonApagarMega_3.sizePolicy().hasHeightForWidth())
        self.ButtonApagarMega_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.ButtonApagarMega_3.setFont(font)
        self.ButtonApagarMega_3.setObjectName("ButtonApagarMega_3")
        self.horizontalLayout_8.addWidget(self.ButtonApagarMega_3)
        self.ButtonWebMega_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonWebMega_3.sizePolicy().hasHeightForWidth())
        self.ButtonWebMega_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.ButtonWebMega_3.setFont(font)
        self.ButtonWebMega_3.setObjectName("ButtonWebMega_3")
        self.horizontalLayout_8.addWidget(self.ButtonWebMega_3)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Mega)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalLayoutWidget.sizePolicy().hasHeightForWidth())
        self.horizontalLayoutWidget.setSizePolicy(sizePolicy)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.textEditMega = QtWidgets.QTextEdit(self.Mega)
        self.textEditMega.setGeometry(QtCore.QRect(10, 140, 461, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditMega.sizePolicy().hasHeightForWidth())
        self.textEditMega.setSizePolicy(sizePolicy)
        self.textEditMega.setObjectName("textEditMega")
        self.EliminarMega = QtWidgets.QGroupBox(self.Mega)
        self.EliminarMega.setGeometry(QtCore.QRect(480, 90, 141, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EliminarMega.sizePolicy().hasHeightForWidth())
        self.EliminarMega.setSizePolicy(sizePolicy)
        self.EliminarMega.setCheckable(True)
        self.EliminarMega.setChecked(False)
        self.EliminarMega.setObjectName("EliminarMega")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.EliminarMega)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 111, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalLayoutWidget_3.sizePolicy().hasHeightForWidth())
        self.verticalLayoutWidget_3.setSizePolicy(sizePolicy)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.Restricoes_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.Restricoes_3.setContentsMargins(0, 0, 0, 0)
        self.Restricoes_3.setObjectName("Restricoes_3")
        self.ListaMega1_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaMega1_3.sizePolicy().hasHeightForWidth())
        self.ListaMega1_3.setSizePolicy(sizePolicy)
        self.ListaMega1_3.setObjectName("ListaMega1_3")
        self.Restricoes_3.addWidget(self.ListaMega1_3)
        self.ListaMega2_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaMega2_3.sizePolicy().hasHeightForWidth())
        self.ListaMega2_3.setSizePolicy(sizePolicy)
        self.ListaMega2_3.setObjectName("ListaMega2_3")
        self.Restricoes_3.addWidget(self.ListaMega2_3)
        self.ListaMega3_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaMega3_3.sizePolicy().hasHeightForWidth())
        self.ListaMega3_3.setSizePolicy(sizePolicy)
        self.ListaMega3_3.setObjectName("ListaMega3_3")
        self.Restricoes_3.addWidget(self.ListaMega3_3)
        self.ListaMega4_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaMega4_3.sizePolicy().hasHeightForWidth())
        self.ListaMega4_3.setSizePolicy(sizePolicy)
        self.ListaMega4_3.setObjectName("ListaMega4_3")
        self.Restricoes_3.addWidget(self.ListaMega4_3)
        self.ListaMega5_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaMega5_3.sizePolicy().hasHeightForWidth())
        self.ListaMega5_3.setSizePolicy(sizePolicy)
        self.ListaMega5_3.setObjectName("ListaMega5_3")
        self.Restricoes_3.addWidget(self.ListaMega5_3)
        self.ListaMega6_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaMega6_3.sizePolicy().hasHeightForWidth())
        self.ListaMega6_3.setSizePolicy(sizePolicy)
        self.ListaMega6_3.setObjectName("ListaMega6_3")
        self.Restricoes_3.addWidget(self.ListaMega6_3)
        self.ListaMega7_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaMega7_3.sizePolicy().hasHeightForWidth())
        self.ListaMega7_3.setSizePolicy(sizePolicy)
        self.ListaMega7_3.setObjectName("ListaMega7_3")
        self.Restricoes_3.addWidget(self.ListaMega7_3)
        self.ListaMega8_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaMega8_3.sizePolicy().hasHeightForWidth())
        self.ListaMega8_3.setSizePolicy(sizePolicy)
        self.ListaMega8_3.setObjectName("ListaMega8_3")
        self.Restricoes_3.addWidget(self.ListaMega8_3)
        self.Loto = QtWidgets.QWidget()
        self.Loto.setObjectName("Loto")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.Loto)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 50, 461, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalLayoutWidget_3.sizePolicy().hasHeightForWidth())
        self.horizontalLayoutWidget_3.setSizePolicy(sizePolicy)
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.spinBoxDezenasLoto = QtWidgets.QSpinBox(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxDezenasLoto.sizePolicy().hasHeightForWidth())
        self.spinBoxDezenasLoto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxDezenasLoto.setFont(font)
        self.spinBoxDezenasLoto.setMinimum(15)
        self.spinBoxDezenasLoto.setMaximum(18)
        self.spinBoxDezenasLoto.setObjectName("spinBoxDezenasLoto")
        self.horizontalLayout_10.addWidget(self.spinBoxDezenasLoto)
        spacerItem2 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.spinBoxJogosLoto = QtWidgets.QSpinBox(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxJogosLoto.sizePolicy().hasHeightForWidth())
        self.spinBoxJogosLoto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxJogosLoto.setFont(font)
        self.spinBoxJogosLoto.setMinimum(1)
        self.spinBoxJogosLoto.setMaximum(100)
        self.spinBoxJogosLoto.setObjectName("spinBoxJogosLoto")
        self.horizontalLayout_10.addWidget(self.spinBoxJogosLoto)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.Loto)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 100, 461, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalLayoutWidget_6.sizePolicy().hasHeightForWidth())
        self.horizontalLayoutWidget_6.setSizePolicy(sizePolicy)
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.ButtonJogarLoto = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonJogarLoto.sizePolicy().hasHeightForWidth())
        self.ButtonJogarLoto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.ButtonJogarLoto.setFont(font)
        self.ButtonJogarLoto.setObjectName("ButtonJogarLoto")
        self.horizontalLayout_11.addWidget(self.ButtonJogarLoto)
        self.ButtonApagarLoto = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonApagarLoto.sizePolicy().hasHeightForWidth())
        self.ButtonApagarLoto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.ButtonApagarLoto.setFont(font)
        self.ButtonApagarLoto.setObjectName("ButtonApagarLoto")
        self.horizontalLayout_11.addWidget(self.ButtonApagarLoto)
        self.ButtonWebLoto = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonWebLoto.sizePolicy().hasHeightForWidth())
        self.ButtonWebLoto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.ButtonWebLoto.setFont(font)
        self.ButtonWebLoto.setObjectName("ButtonWebLoto")
        self.horizontalLayout_11.addWidget(self.ButtonWebLoto)
        self.EliminarLoto = QtWidgets.QGroupBox(self.Loto)
        self.EliminarLoto.setGeometry(QtCore.QRect(480, 90, 141, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EliminarLoto.sizePolicy().hasHeightForWidth())
        self.EliminarLoto.setSizePolicy(sizePolicy)
        self.EliminarLoto.setCheckable(True)
        self.EliminarLoto.setChecked(False)
        self.EliminarLoto.setObjectName("EliminarLoto")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.EliminarLoto)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 111, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalLayoutWidget_4.sizePolicy().hasHeightForWidth())
        self.verticalLayoutWidget_4.setSizePolicy(sizePolicy)
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.Restricoes_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.Restricoes_4.setContentsMargins(0, 0, 0, 0)
        self.Restricoes_4.setObjectName("Restricoes_4")
        self.ListaLoto1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaLoto1.sizePolicy().hasHeightForWidth())
        self.ListaLoto1.setSizePolicy(sizePolicy)
        self.ListaLoto1.setObjectName("ListaLoto1")
        self.Restricoes_4.addWidget(self.ListaLoto1)
        self.ListaLoto2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaLoto2.sizePolicy().hasHeightForWidth())
        self.ListaLoto2.setSizePolicy(sizePolicy)
        self.ListaLoto2.setObjectName("ListaLoto2")
        self.Restricoes_4.addWidget(self.ListaLoto2)
        self.ListaLoto3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaLoto3.sizePolicy().hasHeightForWidth())
        self.ListaLoto3.setSizePolicy(sizePolicy)
        self.ListaLoto3.setObjectName("ListaLoto3")
        self.Restricoes_4.addWidget(self.ListaLoto3)
        self.ListaLoto4 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaLoto4.sizePolicy().hasHeightForWidth())
        self.ListaLoto4.setSizePolicy(sizePolicy)
        self.ListaLoto4.setObjectName("ListaLoto4")
        self.Restricoes_4.addWidget(self.ListaLoto4)
        self.ListaLoto5 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaLoto5.sizePolicy().hasHeightForWidth())
        self.ListaLoto5.setSizePolicy(sizePolicy)
        self.ListaLoto5.setObjectName("ListaLoto5")
        self.Restricoes_4.addWidget(self.ListaLoto5)
        self.textEditLoto = QtWidgets.QTextEdit(self.Loto)
        self.textEditLoto.setGeometry(QtCore.QRect(10, 140, 461, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditLoto.sizePolicy().hasHeightForWidth())
        self.textEditLoto.setSizePolicy(sizePolicy)
        self.textEditLoto.setObjectName("textEditLoto")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.Loto)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 461, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalLayoutWidget_4.sizePolicy().hasHeightForWidth())
        self.horizontalLayoutWidget_4.setSizePolicy(sizePolicy)
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOp_o = QtWidgets.QMenu(self.menubar)
        self.menuOp_o.setObjectName("menuOp_o")
        self.menuViews = QtWidgets.QMenu(self.menubar)
        self.menuViews.setObjectName("menuViews")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionSalvar = QtWidgets.QAction(MainWindow)
        self.actionSalvar.setObjectName("actionSalvar")
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionJogar = QtWidgets.QAction(MainWindow)
        self.actionJogar.setObjectName("actionJogar")
        self.actionWeb = QtWidgets.QAction(MainWindow)
        self.actionWeb.setObjectName("actionWeb")
        self.actionApagar_Jogos = QtWidgets.QAction(MainWindow)
        self.actionApagar_Jogos.setObjectName("actionApagar_Jogos")
        self.actionTabbed_view = QtWidgets.QAction(MainWindow)
        self.actionTabbed_view.setObjectName("actionTabbed_view")
        self.actionTile_view = QtWidgets.QAction(MainWindow)
        self.actionTile_view.setObjectName("actionTile_view")
        self.actionSobre_o_desenvolvedor = QtWidgets.QAction(MainWindow)
        self.actionSobre_o_desenvolvedor.setObjectName("actionSobre_o_desenvolvedor")
        self.actionLog_de_Atualiza_es = QtWidgets.QAction(MainWindow)
        self.actionLog_de_Atualiza_es.setObjectName("actionLog_de_Atualiza_es")
        self.menuFile.addAction(self.actionAbrir)
        self.menuFile.addAction(self.actionSalvar)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSair)
        self.menuOp_o.addAction(self.actionJogar)
        self.menuOp_o.addAction(self.actionWeb)
        self.menuOp_o.addAction(self.actionApagar_Jogos)
        self.menuViews.addAction(self.actionTabbed_view)
        self.menuViews.addAction(self.actionTile_view)
        self.menuAbout.addAction(self.actionSobre_o_desenvolvedor)
        self.menuAbout.addAction(self.actionLog_de_Atualiza_es)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOp_o.menuAction())
        self.menubar.addAction(self.menuViews.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LOTERIAS V1.0.1"))
        self.label.setText(_translate("MainWindow", "LOTERIAS"))
        self.Mega.setWindowTitle(_translate("MainWindow", "MEGA SENA"))
        self.ButtonJogarMega_3.setText(_translate("MainWindow", "JOGAR"))
        self.ButtonApagarMega_3.setText(_translate("MainWindow", "APAGAR JOGOS"))
        self.ButtonWebMega_3.setText(_translate("MainWindow", "WEB"))
        self.label_7.setText(_translate("MainWindow", "Quantidade de dezenas"))
        self.label_8.setText(_translate("MainWindow", "Quantidade de jogos"))
        self.EliminarMega.setTitle(_translate("MainWindow", "Eliminar números"))
        self.ListaMega1_3.setText(_translate("MainWindow", "( 01 ~ 10 )"))
        self.ListaMega2_3.setText(_translate("MainWindow", "( 11 ~ 20 )"))
        self.ListaMega3_3.setText(_translate("MainWindow", "( 21 ~ 30 )"))
        self.ListaMega4_3.setText(_translate("MainWindow", "( 31 ~ 40 )"))
        self.ListaMega5_3.setText(_translate("MainWindow", "( 41 ~ 50)"))
        self.ListaMega6_3.setText(_translate("MainWindow", "( 51 ~ 60 )"))
        self.ListaMega7_3.setText(_translate("MainWindow", "( 01 ~ 30 )"))
        self.ListaMega8_3.setText(_translate("MainWindow", "( 31 ~ 60 )"))
        self.Loto.setWindowTitle(_translate("MainWindow", "LOTOFACIL"))
        self.ButtonJogarLoto.setText(_translate("MainWindow", "JOGAR"))
        self.ButtonApagarLoto.setText(_translate("MainWindow", "APAGAR JOGOS"))
        self.ButtonWebLoto.setText(_translate("MainWindow", "WEB"))
        self.EliminarLoto.setTitle(_translate("MainWindow", "Eliminar números"))
        self.ListaLoto1.setText(_translate("MainWindow", "( 01 ~ 05 )"))
        self.ListaLoto2.setText(_translate("MainWindow", "( 06 ~ 10 )"))
        self.ListaLoto3.setText(_translate("MainWindow", "( 11 ~ 15 )"))
        self.ListaLoto4.setText(_translate("MainWindow", "( 16 ~ 20 )"))
        self.ListaLoto5.setText(_translate("MainWindow", "( 21 ~ 25)"))
        self.label_9.setText(_translate("MainWindow", "Quantidade de dezenas"))
        self.label_10.setText(_translate("MainWindow", "Quantidade de jogos"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOp_o.setTitle(_translate("MainWindow", "Opção"))
        self.menuViews.setTitle(_translate("MainWindow", "Views"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir"))
        self.actionAbrir.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSalvar.setText(_translate("MainWindow", "Salvar"))
        self.actionSalvar.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
        self.actionSair.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionJogar.setText(_translate("MainWindow", "Jogar"))
        self.actionJogar.setShortcut(_translate("MainWindow", "Ctrl+J"))
        self.actionWeb.setText(_translate("MainWindow", "Web"))
        self.actionWeb.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionApagar_Jogos.setText(_translate("MainWindow", "Apagar Jogos"))
        self.actionApagar_Jogos.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionTabbed_view.setText(_translate("MainWindow", "Tabbed view"))
        self.actionTabbed_view.setShortcut(_translate("MainWindow", "Shift+T"))
        self.actionTile_view.setText(_translate("MainWindow", "Tile view"))
        self.actionTile_view.setShortcut(_translate("MainWindow", "Shift+V"))
        self.actionSobre_o_desenvolvedor.setText(_translate("MainWindow", "Sobre o desenvolvedor"))
        self.actionLog_de_Atualiza_es.setText(_translate("MainWindow", "Log de Atualizações"))


