# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loterias.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 509)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(650, 509))
        MainWindow.setMaximumSize(QtCore.QSize(650, 509))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(520, 0, 121, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(8)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumber.setObjectName("lcdNumber")
        self.labelDate = QtWidgets.QLabel(self.centralwidget)
        self.labelDate.setGeometry(QtCore.QRect(5, 0, 171, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDate.sizePolicy().hasHeightForWidth())
        self.labelDate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelDate.setFont(font)
        self.labelDate.setText("")
        self.labelDate.setObjectName("labelDate")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 30, 211, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 89, 631, 361))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.mega = QtWidgets.QWidget()
        self.mega.setObjectName("mega")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.mega)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalLayoutWidget.sizePolicy().hasHeightForWidth())
        self.horizontalLayoutWidget.setSizePolicy(sizePolicy)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.mega)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 461, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalLayoutWidget_2.sizePolicy().hasHeightForWidth())
        self.horizontalLayoutWidget_2.setSizePolicy(sizePolicy)
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.spinBoxDezenasMega = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxDezenasMega.sizePolicy().hasHeightForWidth())
        self.spinBoxDezenasMega.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxDezenasMega.setFont(font)
        self.spinBoxDezenasMega.setWrapping(True)
        self.spinBoxDezenasMega.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBoxDezenasMega.setProperty("showGroupSeparator", False)
        self.spinBoxDezenasMega.setMinimum(6)
        self.spinBoxDezenasMega.setMaximum(15)
        self.spinBoxDezenasMega.setObjectName("spinBoxDezenasMega")
        self.horizontalLayout_2.addWidget(self.spinBoxDezenasMega)
        spacerItem1 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.spinBoxJogosMega = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxJogosMega.sizePolicy().hasHeightForWidth())
        self.spinBoxJogosMega.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxJogosMega.setFont(font)
        self.spinBoxJogosMega.setWrapping(False)
        self.spinBoxJogosMega.setProperty("showGroupSeparator", False)
        self.spinBoxJogosMega.setMinimum(1)
        self.spinBoxJogosMega.setMaximum(100)
        self.spinBoxJogosMega.setObjectName("spinBoxJogosMega")
        self.horizontalLayout_2.addWidget(self.spinBoxJogosMega)
        self.textEditMega = QtWidgets.QTextEdit(self.mega)
        self.textEditMega.setGeometry(QtCore.QRect(10, 140, 461, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditMega.sizePolicy().hasHeightForWidth())
        self.textEditMega.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditMega.setFont(font)
        self.textEditMega.setStyleSheet("border: 1px solid;\n"
"border-radius: 10px;")
        self.textEditMega.setObjectName("textEditMega")
        self.EliminarMega = QtWidgets.QGroupBox(self.mega)
        self.EliminarMega.setGeometry(QtCore.QRect(480, 90, 141, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EliminarMega.sizePolicy().hasHeightForWidth())
        self.EliminarMega.setSizePolicy(sizePolicy)
        self.EliminarMega.setCheckable(True)
        self.EliminarMega.setChecked(False)
        self.EliminarMega.setObjectName("EliminarMega")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.EliminarMega)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 111, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalLayoutWidget.sizePolicy().hasHeightForWidth())
        self.verticalLayoutWidget.setSizePolicy(sizePolicy)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Restricoes = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Restricoes.setContentsMargins(0, 0, 0, 0)
        self.Restricoes.setObjectName("Restricoes")
        self.ListaMega1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaMega1.sizePolicy().hasHeightForWidth())
        self.ListaMega1.setSizePolicy(sizePolicy)
        self.ListaMega1.setObjectName("ListaMega1")
        self.Restricoes.addWidget(self.ListaMega1)
        self.ListaMega2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaMega2.sizePolicy().hasHeightForWidth())
        self.ListaMega2.setSizePolicy(sizePolicy)
        self.ListaMega2.setObjectName("ListaMega2")
        self.Restricoes.addWidget(self.ListaMega2)
        self.ListaMega3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaMega3.sizePolicy().hasHeightForWidth())
        self.ListaMega3.setSizePolicy(sizePolicy)
        self.ListaMega3.setObjectName("ListaMega3")
        self.Restricoes.addWidget(self.ListaMega3)
        self.ListaMega4 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaMega4.sizePolicy().hasHeightForWidth())
        self.ListaMega4.setSizePolicy(sizePolicy)
        self.ListaMega4.setObjectName("ListaMega4")
        self.Restricoes.addWidget(self.ListaMega4)
        self.ListaMega5 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaMega5.sizePolicy().hasHeightForWidth())
        self.ListaMega5.setSizePolicy(sizePolicy)
        self.ListaMega5.setObjectName("ListaMega5")
        self.Restricoes.addWidget(self.ListaMega5)
        self.ListaMega6 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaMega6.sizePolicy().hasHeightForWidth())
        self.ListaMega6.setSizePolicy(sizePolicy)
        self.ListaMega6.setObjectName("ListaMega6")
        self.Restricoes.addWidget(self.ListaMega6)
        self.ListaMega7 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaMega7.sizePolicy().hasHeightForWidth())
        self.ListaMega7.setSizePolicy(sizePolicy)
        self.ListaMega7.setObjectName("ListaMega7")
        self.Restricoes.addWidget(self.ListaMega7)
        self.ListaMega8 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaMega8.sizePolicy().hasHeightForWidth())
        self.ListaMega8.setSizePolicy(sizePolicy)
        self.ListaMega8.setObjectName("ListaMega8")
        self.Restricoes.addWidget(self.ListaMega8)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.mega)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 100, 461, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalLayoutWidget_7.sizePolicy().hasHeightForWidth())
        self.horizontalLayoutWidget_7.setSizePolicy(sizePolicy)
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ButtonJogarMega = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonJogarMega.sizePolicy().hasHeightForWidth())
        self.ButtonJogarMega.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonJogarMega.setFont(font)
        self.ButtonJogarMega.setStyleSheet("color: white;\n"
"background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #88d, stop: 0.1 #99e, stop: 0.49 #77c, stop: 0.5 #66b, stop: 1 #77c);\n"
"border-width: 1px;\n"
"border-color: #339;\n"
"border-style: solid;\n"
"border-radius: 7;\n"
"padding: 3px;\n"
"font-size: 11px bold;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"")
        self.ButtonJogarMega.setObjectName("ButtonJogarMega")
        self.horizontalLayout_7.addWidget(self.ButtonJogarMega)
        self.ButtonApagarMega = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonApagarMega.sizePolicy().hasHeightForWidth())
        self.ButtonApagarMega.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonApagarMega.setFont(font)
        self.ButtonApagarMega.setStyleSheet("color: white;\n"
"background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #88d, stop: 0.1 #99e, stop: 0.49 #77c, stop: 0.5 #66b, stop: 1 #77c);\n"
"border-width: 1px;\n"
"border-color: #339;\n"
"border-style: solid;\n"
"border-radius: 7;\n"
"padding: 3px;\n"
"font-size: 11px bold;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"")
        self.ButtonApagarMega.setObjectName("ButtonApagarMega")
        self.horizontalLayout_7.addWidget(self.ButtonApagarMega)
        self.ButtonWebMega = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonWebMega.sizePolicy().hasHeightForWidth())
        self.ButtonWebMega.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonWebMega.setFont(font)
        self.ButtonWebMega.setStyleSheet("color: white;\n"
"background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #88d, stop: 0.1 #99e, stop: 0.49 #77c, stop: 0.5 #66b, stop: 1 #77c);\n"
"border-width: 1px;\n"
"border-color: #339;\n"
"border-style: solid;\n"
"border-radius: 7;\n"
"padding: 3px;\n"
"font-size: 11px bold;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"")
        self.ButtonWebMega.setObjectName("ButtonWebMega")
        self.horizontalLayout_7.addWidget(self.ButtonWebMega)
        self.tabWidget.addTab(self.mega, "")
        self.loto = QtWidgets.QWidget()
        self.loto.setObjectName("loto")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.loto)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 50, 461, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalLayoutWidget_3.sizePolicy().hasHeightForWidth())
        self.horizontalLayoutWidget_3.setSizePolicy(sizePolicy)
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.spinBoxDezenasLoto = QtWidgets.QSpinBox(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxDezenasLoto.sizePolicy().hasHeightForWidth())
        self.spinBoxDezenasLoto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxDezenasLoto.setFont(font)
        self.spinBoxDezenasLoto.setWrapping(True)
        self.spinBoxDezenasLoto.setMinimum(15)
        self.spinBoxDezenasLoto.setMaximum(18)
        self.spinBoxDezenasLoto.setObjectName("spinBoxDezenasLoto")
        self.horizontalLayout_3.addWidget(self.spinBoxDezenasLoto)
        spacerItem2 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.spinBoxJogosLoto = QtWidgets.QSpinBox(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxJogosLoto.sizePolicy().hasHeightForWidth())
        self.spinBoxJogosLoto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxJogosLoto.setFont(font)
        self.spinBoxJogosLoto.setMinimum(1)
        self.spinBoxJogosLoto.setMaximum(100)
        self.spinBoxJogosLoto.setObjectName("spinBoxJogosLoto")
        self.horizontalLayout_3.addWidget(self.spinBoxJogosLoto)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.loto)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 100, 461, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalLayoutWidget_6.sizePolicy().hasHeightForWidth())
        self.horizontalLayoutWidget_6.setSizePolicy(sizePolicy)
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ButtonJogarLoto = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonJogarLoto.sizePolicy().hasHeightForWidth())
        self.ButtonJogarLoto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.ButtonJogarLoto.setFont(font)
        self.ButtonJogarLoto.setStyleSheet("color: white;\n"
"background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #88d, stop: 0.1 #99e, stop: 0.49 #77c, stop: 0.5 #66b, stop: 1 #77c);\n"
"border-width: 1px;\n"
"border-color: #339;\n"
"border-style: solid;\n"
"border-radius: 7;\n"
"padding: 3px;\n"
"font-size: 11px bold;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"")
        self.ButtonJogarLoto.setObjectName("ButtonJogarLoto")
        self.horizontalLayout_6.addWidget(self.ButtonJogarLoto)
        self.ButtonApagarLoto = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonApagarLoto.sizePolicy().hasHeightForWidth())
        self.ButtonApagarLoto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.ButtonApagarLoto.setFont(font)
        self.ButtonApagarLoto.setStyleSheet("color: white;\n"
"background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #88d, stop: 0.1 #99e, stop: 0.49 #77c, stop: 0.5 #66b, stop: 1 #77c);\n"
"border-width: 1px;\n"
"border-color: #339;\n"
"border-style: solid;\n"
"border-radius: 7;\n"
"padding: 3px;\n"
"font-size: 11px bold;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"")
        self.ButtonApagarLoto.setObjectName("ButtonApagarLoto")
        self.horizontalLayout_6.addWidget(self.ButtonApagarLoto)
        self.ButtonWebLoto = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonWebLoto.sizePolicy().hasHeightForWidth())
        self.ButtonWebLoto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.ButtonWebLoto.setFont(font)
        self.ButtonWebLoto.setStyleSheet("color: white;\n"
"background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #88d, stop: 0.1 #99e, stop: 0.49 #77c, stop: 0.5 #66b, stop: 1 #77c);\n"
"border-width: 1px;\n"
"border-color: #339;\n"
"border-style: solid;\n"
"border-radius: 7;\n"
"padding: 3px;\n"
"font-size: 11px bold;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"")
        self.ButtonWebLoto.setObjectName("ButtonWebLoto")
        self.horizontalLayout_6.addWidget(self.ButtonWebLoto)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.loto)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 461, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalLayoutWidget_4.sizePolicy().hasHeightForWidth())
        self.horizontalLayoutWidget_4.setSizePolicy(sizePolicy)
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.textEditLoto = QtWidgets.QTextEdit(self.loto)
        self.textEditLoto.setGeometry(QtCore.QRect(10, 140, 461, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditLoto.sizePolicy().hasHeightForWidth())
        self.textEditLoto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditLoto.setFont(font)
        self.textEditLoto.setStyleSheet("border: 1px solid;\n"
"border-radius: 10px;")
        self.textEditLoto.setObjectName("textEditLoto")
        self.EliminarLoto = QtWidgets.QGroupBox(self.loto)
        self.EliminarLoto.setGeometry(QtCore.QRect(480, 90, 141, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EliminarLoto.sizePolicy().hasHeightForWidth())
        self.EliminarLoto.setSizePolicy(sizePolicy)
        self.EliminarLoto.setCheckable(True)
        self.EliminarLoto.setChecked(False)
        self.EliminarLoto.setObjectName("EliminarLoto")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.EliminarLoto)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 111, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalLayoutWidget_2.sizePolicy().hasHeightForWidth())
        self.verticalLayoutWidget_2.setSizePolicy(sizePolicy)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.Restricoes_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.Restricoes_2.setContentsMargins(0, 0, 0, 0)
        self.Restricoes_2.setObjectName("Restricoes_2")
        self.ListaLoto1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaLoto1.sizePolicy().hasHeightForWidth())
        self.ListaLoto1.setSizePolicy(sizePolicy)
        self.ListaLoto1.setObjectName("ListaLoto1")
        self.Restricoes_2.addWidget(self.ListaLoto1)
        self.ListaLoto2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaLoto2.sizePolicy().hasHeightForWidth())
        self.ListaLoto2.setSizePolicy(sizePolicy)
        self.ListaLoto2.setObjectName("ListaLoto2")
        self.Restricoes_2.addWidget(self.ListaLoto2)
        self.ListaLoto3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaLoto3.sizePolicy().hasHeightForWidth())
        self.ListaLoto3.setSizePolicy(sizePolicy)
        self.ListaLoto3.setObjectName("ListaLoto3")
        self.Restricoes_2.addWidget(self.ListaLoto3)
        self.ListaLoto4 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaLoto4.sizePolicy().hasHeightForWidth())
        self.ListaLoto4.setSizePolicy(sizePolicy)
        self.ListaLoto4.setObjectName("ListaLoto4")
        self.Restricoes_2.addWidget(self.ListaLoto4)
        self.ListaLoto5 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaLoto5.sizePolicy().hasHeightForWidth())
        self.ListaLoto5.setSizePolicy(sizePolicy)
        self.ListaLoto5.setObjectName("ListaLoto5")
        self.Restricoes_2.addWidget(self.ListaLoto5)
        self.tabWidget.addTab(self.loto, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOp_o = QtWidgets.QMenu(self.menubar)
        self.menuOp_o.setObjectName("menuOp_o")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionSalvar = QtWidgets.QAction(MainWindow)
        self.actionSalvar.setObjectName("actionSalvar")
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionJogar = QtWidgets.QAction(MainWindow)
        self.actionJogar.setObjectName("actionJogar")
        self.actionWeb = QtWidgets.QAction(MainWindow)
        self.actionWeb.setObjectName("actionWeb")
        self.actionApagar_Jogos = QtWidgets.QAction(MainWindow)
        self.actionApagar_Jogos.setObjectName("actionApagar_Jogos")
        self.actionSobre_o_desenvolvedor = QtWidgets.QAction(MainWindow)
        self.actionSobre_o_desenvolvedor.setObjectName("actionSobre_o_desenvolvedor")
        self.actionLog_de_Atualiza_es = QtWidgets.QAction(MainWindow)
        self.actionLog_de_Atualiza_es.setObjectName("actionLog_de_Atualiza_es")
        self.menuFile.addAction(self.actionAbrir)
        self.menuFile.addAction(self.actionSalvar)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSair)
        self.menuOp_o.addAction(self.actionJogar)
        self.menuOp_o.addAction(self.actionWeb)
        self.menuOp_o.addAction(self.actionApagar_Jogos)
        self.menuAbout.addAction(self.actionSobre_o_desenvolvedor)
        self.menuAbout.addAction(self.actionLog_de_Atualiza_es)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOp_o.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LOTERIAS V1.0.0"))
        self.label.setText(_translate("MainWindow", "LOTERIAS"))
        self.label_2.setText(_translate("MainWindow", "Quantidade de dezenas"))
        self.label_3.setText(_translate("MainWindow", "Quantidade de jogos"))
        self.EliminarMega.setTitle(_translate("MainWindow", "Eliminar números"))
        self.ListaMega1.setText(_translate("MainWindow", "( 01 ~ 10 )"))
        self.ListaMega2.setText(_translate("MainWindow", "( 11 ~ 20 )"))
        self.ListaMega3.setText(_translate("MainWindow", "( 21 ~ 30 )"))
        self.ListaMega4.setText(_translate("MainWindow", "( 31 ~ 40 )"))
        self.ListaMega5.setText(_translate("MainWindow", "( 41 ~ 50 )"))
        self.ListaMega6.setText(_translate("MainWindow", "( 51 ~ 60 )"))
        self.ListaMega7.setText(_translate("MainWindow", "( 01 ~ 30 )"))
        self.ListaMega8.setText(_translate("MainWindow", "( 31 ~ 60 )"))
        self.ButtonJogarMega.setText(_translate("MainWindow", "JOGAR"))
        self.ButtonApagarMega.setText(_translate("MainWindow", "APAGAR JOGOS"))
        self.ButtonWebMega.setText(_translate("MainWindow", "WEB"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mega), _translate("MainWindow", "MEGA SENA"))
        self.ButtonJogarLoto.setText(_translate("MainWindow", "JOGAR"))
        self.ButtonApagarLoto.setText(_translate("MainWindow", "APAGAR JOGOS"))
        self.ButtonWebLoto.setText(_translate("MainWindow", "WEB"))
        self.label_4.setText(_translate("MainWindow", "Quantidade de dezenas"))
        self.label_5.setText(_translate("MainWindow", "Quantidade de jogos"))
        self.EliminarLoto.setTitle(_translate("MainWindow", "Eliminar números"))
        self.ListaLoto1.setText(_translate("MainWindow", "( 01 ~ 05 )"))
        self.ListaLoto2.setText(_translate("MainWindow", "( 06 ~ 10 )"))
        self.ListaLoto3.setText(_translate("MainWindow", "( 11 ~ 15 )"))
        self.ListaLoto4.setText(_translate("MainWindow", "( 16 ~ 20 )"))
        self.ListaLoto5.setText(_translate("MainWindow", "( 21 ~ 25 )"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.loto), _translate("MainWindow", "LOTO FACIL"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOp_o.setTitle(_translate("MainWindow", "Opção"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir"))
        self.actionAbrir.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSalvar.setText(_translate("MainWindow", "Salvar"))
        self.actionSalvar.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
        self.actionSair.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionJogar.setText(_translate("MainWindow", "Jogar"))
        self.actionJogar.setShortcut(_translate("MainWindow", "Ctrl+J"))
        self.actionWeb.setText(_translate("MainWindow", "Web"))
        self.actionWeb.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionApagar_Jogos.setText(_translate("MainWindow", "Apagar Jogos"))
        self.actionApagar_Jogos.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionSobre_o_desenvolvedor.setText(_translate("MainWindow", "Sobre o desenvolvedor"))
        self.actionLog_de_Atualiza_es.setText(_translate("MainWindow", "Log de Atualizações"))


